### ISSUE TITLE
Ability to return Jacobians and Sensitivity Matrices

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#10]
This will require adding hard coding partial derivatives for each built in propensity type:
Jacobian: $\frac{d \rho_i(s)}{ds_j}$ for each species $s_j$
Sensitivity Matrix: $\frac{d \rho_i(s)}{dk}$ for each parameter (of that propensity) $k$.

Note: we will also need a check to make sure parameters aren't changing due to rules. If rules effect parameters, the sensitivity matrix will not be accurate and a warning should be given.

**Comment by WilliamIX** [comment]
@ayush9pandey do you think we can close this issue given your new code?

**Comment by ayush9pandey** [comment]
Yes :D but I need to create the PR from that branch first. Will do this right now.

**Comment by ayush9pandey** [comment]
> 
> 
> @ayush9pandey do you think we can close this issue given your new code?

I looked into that a bit and it definitely seems possible from the code point of view but 
1. We would need a proper example to demonstrate how Jacobian helps with odeint
2. Maybe need some Cythonizing before we implement this because in that case odeint will evaluate the Jacobian function at every time point.

**Comment by ayush9pandey** [comment]
Fixed with #111
