### ISSUE TITLE
distributing bioscrape binaries through conda-forge

### ISSUE THREAD

**Issue by zoltuz** [biocircuits/bioscrape#51]
Hi all,

I've looked at the [installation process](https://github.com/biocircuits/bioscrape/wiki/Installation) for bioscrape and it requires a lot from a user who would just want to simulate some SBML files.  I'd like to suggest a different approach, which makes the installation easy for the user but, in exchange, it requires a bit of work from the developers. 

The [Conda](https://docs.conda.io/en/latest/) package manager distributes binaries of python packages, instead of the source code of a package (like pip install)! Thus, all the compiling steps and the required toolchain for compilation can be ignored by the user (who just wants to use the package, but not develop it).  

The end results of this new process would be very simple for the user:

Installing bioscrape from the conda-forge channel can be achieved by adding conda-forge to your channels with:
```
conda config --add channels conda-forge
```
Once the conda-forge channel has been enabled, bioscrape can be installed with:
```
conda install bioscrape
```

The main steps of this process for the developers:
 * installing conda and conda-build 
 * creating a conda recipe (take some time to nail down the correct build recipe) 
 * add conda build to the Travis CI (the recipe is constantly tested)
 * sending the build recipe to conda-forge, this makes the package conda installable 
 * sending new versions of bioscrape to conda-forge (through automated deployment, e.g. triggered by a merge into the master branch)

Let me know if you are interested in this, I'm happy to team up with someone and make this happen!

**Comment by WilliamIX** [comment]
@zoltuz as mentioned I would love to try to make this work. @sclamons do you have any experience here?

**Comment by sclamons** [comment]
The closest I've done was to distribute a (pip-installable) package through Pypi. I've never worked directly with conda except as a user.

**Comment by murrayrm** [comment]
I have intermediate level expertise in conda-forge.

**Comment by murrayrm** [comment]
A couple of notes on what I think we are going to need to do in order to use conda-forge:

* We need to set up the bioscrape package on pypi, so that it can be installed via pip.  This likely requires a few changes to the package:

    * We need to use a "standard" `setup.py` file that uses `setuptools`.
    * We need to create proper versioning

* We need to create a conda-forge feedstock for bioscrape.  Directions for that are [here](https://github.com/conda-forge/staged-recipes).

@WilliamIX @zoltuz Comments on `setup.py` and versioning?

**Comment by WilliamIX** [comment]
Update on this issue: recently I made bioscrape pip installable by configuring pip to compile the cython code when on install. This works for anyone who has a C++ compiler set up.

The other way to solve this problem is to produce and maintain many precompiled versions of bioscrape for different chip architectures (minimally we would need a few Linux varieties, Windows Intel and Windows AMD, and a couple Mac OS varieties). In principle, this could be automated via a github action to produce the required python wheels for each architecture. In practice, configuring github actions to do this is challenging and requires interfacing with things like Docker. Given that pip install currently works I think that setting up automatic wheel generation is not a priority.

**Comment by murrayrm** [comment]
I think that conda-forge can create all of these versions once thing are on `pypi` (which is looks like they are).

I won't have time to do this anytime soon, but if anyone wants to take it on I can help.  See https://anaconda.org/conda-forge/slycot for an example of a feedstock that does Linux, Windows, and Mac.  I don't think Windows AMD or MacOS M1 are yet supported, but those users can always build via pip.

Q: is a C/C++ compiler required if you use want to _use_ bioscrape?  If not, I think it will increase usage to have compiled version on standard platforms.

**Comment by WilliamIX** [comment]
Solved via clever pip work arounds. TODO is to set up automatic generation of compiled python wheels for auto installation.
