### ISSUE TITLE
General propensity needs underscored parameters, also rules.

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#59]
General propensity needs parameters with underscores in its rate law while other propensities can be created without this. Same thing for rules equations. 

Is there a way to implement this so that this is no longer the case? I realize that for both of these things we are using underscores to differentiate between parameters and species but this kinda creates a confusing user interface..

**Comment by WilliamIX** [comment]
I think we should definitely try to make an implementation that doesn't use this frustrating convention. Here is a proposal:

All CRN species are given in the species list and defined with the CRN (via SBML or the API). If something isn't in the Species list, it is a parameter, by default.

In order to make this change, we will have to work on the sympy formula parsing code in particular - and ideally make it fast.
We will also need to add checks when getting species and reactions from propensities and rules to make sure all the returned species are in Model.species. If they are not, an error needs to be thrown to ensure that models load correctly without having to backtrack and re-instantiate things.
