### ISSUE TITLE
Do rules work for setting parameter values at a certain time during the simulation? 

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#60]
I have used a heaviside rule before to set a species concentration during a simulation. Does the same thing work for parameters? I think I am not getting expected results when I am doing this.

**Comment by WilliamIX** [comment]
I think this should work, but it's possible there is something I am missing. I typically use assignment rules to dummy species because if things are being assigned, I want to see them in the output.

That said, I totally believe there could be a problem - if you can recreate this with a simple example, I can help get to the bottom of it.
