### ISSUE TITLE
Bioscrape reading SBML annotations incorrectly?

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#61]
From a Slack conversation with Nazmus:

When using bioscrape via BioCRNpyler: function simulate_with_bioscrape_via_sbml first creates an sbml file from the CRN being simulated using self.write_sbml_file(file_name ="temp_sbml_file.xml", stochastic_model = stochastic, for_bioscrape = True) .

I basically tried simulating one CRN two different ways:

1. I saved the CRN without changing the default "for_bioscrape = False" argument and simulated it using bioscrape
```
CRN.write_sbml_file(file_name ="sbml_file.xml") 
sbml = import_sbml("sbml_file.xml")
initial_conc = {{"S1":10,....}}
sbml.set_species(initial_conc) # setting initial concentrations
timepoints = np.linspace(0, 16000, 1000)
R = py_simulate_model(timepoints, Model = sbml)
```

 2.  I simulated the CRN using the built-in BioCRNPyler function simulate_with_bioscrape_via_sbml
`R = CRN.simulate_with_bioscrape_via_sbml(timepoints, initial_condition_dict = initial_conc)`

The results of the simulation were different, even though both were simulated by bioscrape and sbml files created by BioCRNPyler. After spending a lot of time trying to debug it, I figured out that the only difference was the "for_bioscrape" argument for the write_sbml_file function. In the first method, it defaulted to False and in the second method, it is set to True inside the  simulate_with_bioscrape_via_sbml function in BioCRNPyler.

After telling Ayush about all this, he told me that the "for_bioscrape" argument adds annotations for reversible functions to the SBML file. These annotations alone shouldn't cause different simulation results so Ayush suggested I look at the bioscrape_read.xml files for both of the simulations (using sbml.write_bioscrape_xml("bioscrape_read.xml")). The bioscrape_read.xml files showed that bioscrape reads the same parameter for both the forward and backward reaction rates in a reversible reaction for an annotated sbml file. In other words, even if the forward and backward reactions had different rates, only one of those rates was being used for both reactions in Method 2 (the method which created an sbml file with annotations). Method 1 did not have this issue since the sbml file created here didn't have annotations (again since "for_bioscrape" is set to False).

@ayush9pandey concluded that this was happening because bioscrape was incorrectly handling annotations from sbml files that had them. Is this still true? I am asking Nazmus to attach an example file to this issue so we can fix it.

**Comment by ayush9pandey** [comment]
I think the issue was biocrnpyler not writing annotations correctly, that is why I created this issue: https://github.com/BuildACell/BioCRNPyler/issues/174

Is the issue still persistent @Chryron ?

**Comment by WilliamIX** [comment]
Based on the example in the issue you created @ayush9pandey I thought I had fixed it. Nazmus says there still may be an issue and is working on finding a concrete example to show us.

**Comment by Chryron** [comment]
I just double checked the bioscrape_read files and the issue now seems to be caused by something different. It arises when multiple reactions in an sbml file have the same name for one of their reaction rates. For example, reactions 3 and 5 both have the same name for their mass action rate, "k_forward", as shown below.

Reaction 3 SBML 
![Reaction3_sbml](https://user-images.githubusercontent.com/43299520/92656304-9f8dfe80-f314-11ea-9aaa-bf8a464f81d0.png)

k_forward here is 9.530...

Reaction 5 SBML
![Reaction5_sbml](https://user-images.githubusercontent.com/43299520/92656397-cba97f80-f314-11ea-876c-88e22b624c8b.png)
 
k_forward here is 38.857...

When bioscrape reads this sbml file, it correctly imports the values of all rates with the name "k_forward" as shown below:

![parameters](https://user-images.githubusercontent.com/43299520/92656684-496d8b00-f315-11ea-9790-b14728c8e31e.png)

The k_forward for reaction 3 is automatically named k_forward and the one for reaction 5 is named k_forward_r5

However when bioscrape tries to read the reactions, it uses the parameter named "k_forward" with a value of 9.530 for every reaction with the common rate name. This is shown below:

Reaction 3 is read as:
![Reaction3_read](https://user-images.githubusercontent.com/43299520/92657005-d7e20c80-f315-11ea-9a49-00092217c64e.png)

Reaction 5 is read as:
![Reaction5_read](https://user-images.githubusercontent.com/43299520/92656964-c993f080-f315-11ea-9c96-60192ba3c139.png)

**Comment by WilliamIX** [comment]
Thanks @Chryron! this is very helpful.

I think what is going on is that when Bioscrape renames local SBML parameters and makes them global, it does not simultaneously rename the annotation parameters. We need to make sure this happens.

**Comment by WilliamIX** [comment]
This issue has been fixed in Dev and will be pushed to master soon.
